### PR TITLE
Fix Precision Issues in Payment Order Amount Calculations

### LINKED ISSUE #450: Fix Precision Issues in Amount Calculations to Prevent Stuck Funds
**Describe the bug**
Precision errors in amount calculations are causing valid transactions to be incorrectly flagged as insufficient, resulting in funds getting stuck in contracts. The system currently uses fixed decimal approximations (`.Round(4)` and `int32(4)`) instead of the tokens' native decimals.

**To Reproduce**
1. Initiate a payment order with a token that has >4 decimals (e.g., USDC with 6 decimals)
2. Send an amount that would be valid with full precision but fails with 4-decimal rounding
3. Observe the transaction being rejected despite sufficient funds
4. Check contract balance to confirm funds are stuck

**Expected behavior**
1. All calculations should use the token's native decimals
2. Transactions with sufficient funds (including those within 1 subunit tolerance) should process normally
3. No funds should get stuck due to rounding errors

**Environment:**
- All environments (production, staging, development)
- Affects all chain integrations
- First observed: N/A

**Additional context**
Problem locations:
1. `senderFee` calculation in `InitiatePaymentOrder` controller
2. Amount comparisons in `UpdateReceiveAddressStatus` service

Impact:
- Financial losses due to stuck funds
- Poor user experience with failed transactions
- Requires manual intervention to recover funds

### PR DESCRIPTION
**Pull request by sundayonah**
### Description

This PR resolves precision errors in amount calculations within the payment order processing workflow, which were causing valid transactions to be incorrectly flagged as insufficient and resulting in funds getting stuck in contracts. The issue stemmed from fixed 4-decimal rounding approximations (Round(4) and int32(4)) that didn’t account for tokens’ native decimals (e.g., 6 for USDC, 18 for ETH). The changes ensure all calculations use the token’s native precision and introduce a 1-subunit tolerance for amount comparisons, preventing unnecessary rejections and stuck funds.

### Implementation Details:

* InitiatePaymentOrder Controller:
 * Modified `senderFee` calculation from `feePercent.Mul(payload.Amount).Div(100).Round(4)` to .Round(int32(token.Decimals))`.
 * Applied the same precision fix to `protocolFee` for consistency.
 * Ensures the payment order is created with full token-specific precision.

*UpdateReceiveAddressStatus Service:
 * Replaced fixed 4-decimal rounding with `token.Decimals` for `orderAmountWithFees` and `newOrderAmount`.
 * Added a 1-subunit tolerance check using `*big.Int` comparisons `(lowerBound and upperBound)`.
 * Updated logic to only adjust `paymentOrder.Amount` when the transferred amount (`event.Value`) is outside tolerance, preserving the original amount within tolerance and avoiding drift (e.g., 0.00001).
 * Added a check to reject transfers insufficient to cover fees (`newOrderAmount < 0`). 

### References

Closes #450

### Checklist

- [ ] I have added documentation and tests for new/changed functionality in this PR
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c) and [Contribution Guide](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a).

### CODE REVIEW

File: services/indexer.go [hunk 1]
```diff
@@ -1558,6 +1558,11 @@ func (s *IndexerService) UpdateReceiveAddressStatus(
 		fees := paymentOrder.NetworkFee.Add(paymentOrder.SenderFee).Add(paymentOrder.ProtocolFee)
 		orderAmountWithFees := paymentOrder.Amount.Add(fees).Round(int32(paymentOrder.Edges.Token.Decimals))
 		orderAmountWithFeesInSubunit := utils.ToSubunit(orderAmountWithFees, paymentOrder.Edges.Token.Decimals)
+
+		tolerance := big.NewInt(1)
+		lowerBound := new(big.Int).Sub(orderAmountWithFeesInSubunit, tolerance)
+		upperBound := new(big.Int).Add(orderAmountWithFeesInSubunit, tolerance)
+		withinTolerance := event.Value.Cmp(lowerBound) >= 0 && event.Value.Cmp(upperBound) <= 0
```
Comment (onahprosper) [inline services/indexer.go:1565]: is it possible we have a test for this, for instance;
Transferred Value Matches the Expected Amount (Within Tolerance)
Transferred Value is Less Than the Expected Amount and it Insufficient to Cover Fees etc
Imagine a scenerio where:
A user initiates a payment order with an amount of 10.0 tokens.
The network fee is 0.1
The total expected amount with fees is 10.1 tokens.
The transferred value (event.Value) is 10.1 tokens (exact match).

And when the transfer value is less than 10.1 etc

Comment (sundayonah) [reply services/indexer.go:1565]: Yes, it’s absolutely possible to add test cases for the scenarios you described.
