### PR TITLE
Fix Handling of Amounts Below Minimum Bucket in Lock Payment Orders

### LINKED ISSUE #431: Better Handle Provision Bucket When Amount Is Less Than Minimum Bucket
### Describe the Bug
When the amount for a lock payment order is less than the minimum bucket for the currency, the `getProvisionBucket` function returns `nil`, and the system attempts to split the lock payment order, which is not applicable in this case. Instead, the system should handle this scenario by calling `handleCancellation` immediately after detecting that the amount is less than the minimum bucket.

### Expected Behavior
When the amount is less than the minimum bucket for the currency:
1. The `getProvisionBucket` function should return a third parameter indicating whether the amount is less than the minimum bucket.
2. If the amount is less than the minimum bucket, the system should call `handleCancellation` immediately after the declaration/assignment of the `lockPaymentOrder` variable.

### Tech Details
1. Update the `getProvisionBucket` function to return a third parameter (`isLessThanMin`).  
2. Add logic to check if the amount is less than the minimum bucket after the `lockPaymentOrder` declaration/assignment.  
3. Call `handleCancellation` if the amount is less than the minimum bucket.  
4. Write unit tests to verify the new behavior.  

### Proposed Changes
1. **Function Update**:  
   ```go
   func (s *IndexerService) getProvisionBucket(ctx context.Context, amount decimal.Decimal, currency *ent.FiatCurrency) (*ent.ProvisionBucket, bool, error) {
       provisionBucket, err := db.Client.ProvisionBucket.
           Query().
           Where(
               provisionbucket.MaxAmountGTE(amount),
               provisionbucket.MinAmountLTE(amount),
               provisionbucket.HasCurrencyWith(
                   fiatcurrency.IDEQ(currency.ID),
               ),
           ).
           WithCurrency().
           Only(ctx)
       if err != nil {
           if ent.IsNotFound(err) {
               // Check if the amount is less than the minimum bucket
               minBucket, err := db.Client.ProvisionBucket.
                   Query().
                   Where(
                       provisionbucket.HasCurrencyWith(
                           fiatcurrency.IDEQ(currency.ID),
                       ),
                   ).
                   Order(ent.Asc(provisionbucket.FieldMinAmount)).
                   First(ctx)
               if err != nil {
                   return nil, false, fmt.Errorf("failed to fetch minimum bucket: %w", err)
               }
               if amount.LessThan(minBucket.MinAmount) {
                   return nil, true, nil
               }
           }
           return nil, false, fmt.Errorf("failed to fetch provision bucket: %w", err)
       }
       return provisionBucket, false, nil
   }

2. **Logic Update**

```go
provisionBucket, isLessThanMin, err := s.getProvisionBucket(ctx, amountInDecimals.Mul(rate), currency)
if err != nil {
    logger.Errorf("failed to fetch provision bucket: %s %s %v", amountInDecimals, currency, err)
}

// Create lock payment order fields
lockPaymentOrder := types.LockPaymentOrderFields{
    Token:             token,
    Network:           network,
    GatewayID:         gatewayId,
    Amount:            amountInDecimals,
    Rate:              rate,
    BlockNumber:       int64(event.BlockNumber),
    TxHash:            event.TxHash,
    Institution:       recipient.Institution,
    AccountIdentifier: recipient.AccountIdentifier,
    AccountName:       recipient.AccountName,
    ProviderID:        recipient.ProviderID,
    Memo:              recipient.Memo,
    ProvisionBucket:   provisionBucket,
}

if isLessThanMin {
    err := s.handleCancellation(ctx, client, nil, &lockPaymentOrder, "Amount is less than the minimum bucket")
    if err != nil {
        return nil
    }
    return nil
}
```

### Notes/Assumptions
* The `getProvisionBucket` function should return `isLessThanMin` as `true` only when the amount is less than the minimum bucket for the currency.
* The `handleCancellation` function should be called with an appropriate error message when the amount is less than the minimum bucket.

### PR DESCRIPTION
**Pull request by sundayonah**
### Description

This PR addresses a bug in the IndexerService where lock payment orders with amounts less than the minimum provision bucket were incorrectly processed by attempting to split them, rather than being cancelled immediately. The change ensures that such orders are properly cancelled as soon as the condition is detected, improving system reliability and preventing invalid order processing.

### References
closes #431

### Testing

This PR includes unit tests to verify the fix:

* Test Cases Added in TestGetProvisionBucket:
  *  matching_bucket_found_10to100: Verifies correct bucket returned for amount within 10-100 range.
  * matching_bucket_found_100to1000: Verifies correct bucket for 100-1000 range.
  * below_minimum_bucket: Ensures isLessThanMin is true and no error for amounts < 10.
  * above_maximum_bucket: Confirms error returned for amounts > 1000 with no bucket.
  * no_buckets_for_currency: Validates error handling when no buckets exist for a currency.

### Checklist

- [ ] I have added documentation and tests for new/changed functionality in this PR
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c) and [Contribution Guide](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a).

### CODE REVIEW

File: services/indexer.go [hunk 1]
```diff
@@ -1833,11 +1857,19 @@ func (s *IndexerService) splitLockPaymentOrder(ctx context.Context, client types
...
 		}
 
+		if isLessThanMin {
+			err := s.handleCancellation(ctx, client, nil, &lockPaymentOrder, "amount to split below minimum bucket threshold")
+			if err != nil {
+				logger.Errorf("failed to cancel split payment order: %v", err)
+			}
+			return nil // Or return an error if required
+		}
+
```
Comment (chibie) [inline services/indexer.go:1872]: the only change here should be capturing the space for isLessThanMin... but it's not used in splitLockPaymentOrder function.

```
bucket, _, err := s.getProvisionBucket(ctx, amountToSplit, currency)
```

File: services/indexer.go [hunk 2]
```diff
@@ -944,9 +943,9 @@ func (s *IndexerService) CreateLockPaymentOrder(ctx context.Context, client type
 
 	rate := decimal.NewFromBigInt(event.Rate, -2)
 
-	provisionBucket, err := s.getProvisionBucket(ctx, amountInDecimals.Mul(rate), currency)
+	provisionBucket, isLessThanMin, err := s.getProvisionBucket(ctx, amountInDecimals.Mul(rate), currency)
 	if err != nil {
-		logger.Errorf("failed to fetch provision bucket: %s %s %v", amountInDecimals, currency, err)
+		return fmt.Errorf("failed to fetch provision bucket: %w", err)
```
Comment (chibie) [inline services/indexer.go:948]: revert this change... it should only log not return. should stay as

```
logger.Errorf("failed to fetch provision bucket: %s %s %v", amountInDecimals, currency, err)
```

**Review by chibie — CHANGES_REQUESTED** [review]

**Review by chibie — APPROVED** [review]
